export const MOOD_IMAGES: Record<string, any[]> = {
  love: [
    require('@/assets/images/love/1.webp'),
    require('@/assets/images/love/2.webp'),
    require('@/assets/images/love/3.webp'),
    require('@/assets/images/love/4.webp'),
    require('@/assets/images/love/5.webp'),
    require('@/assets/images/love/6.webp'),
    require('@/assets/images/love/7.webp'),
    require('@/assets/images/love/8.webp'),
    require('@/assets/images/love/9.webp'),
    require('@/assets/images/love/10.webp'),
    require('@/assets/images/love/11.webp'),
    require('@/assets/images/love/12.webp'),
    require('@/assets/images/love/13.webp'),
    require('@/assets/images/love/14.webp'),
    require('@/assets/images/love/15.webp'),
    require('@/assets/images/love/16.webp'),
    require('@/assets/images/love/17.webp'),
    require('@/assets/images/love/18.webp'),
    require('@/assets/images/love/19.webp'),
    require('@/assets/images/love/20.webp'),
    require('@/assets/images/love/21.webp'),
    require('@/assets/images/love/22.webp'),
    require('@/assets/images/love/23.webp'),
    require('@/assets/images/love/24.webp'),
    require('@/assets/images/love/25.webp'),
    require('@/assets/images/love/26.webp'),
    require('@/assets/images/love/27.webp'),
    require('@/assets/images/love/28.webp'),
    require('@/assets/images/love/29.webp'),
    require('@/assets/images/love/30.webp'),
    require('@/assets/images/love/31.webp'),
  ],
  calm: [
    require('@/assets/images/calm/1.webp'),
    require('@/assets/images/calm/2.webp'),
    require('@/assets/images/calm/3.webp'),
    require('@/assets/images/calm/4.webp'),
    require('@/assets/images/calm/5.webp'),
    require('@/assets/images/calm/6.webp'),
    require('@/assets/images/calm/7.webp'),
    require('@/assets/images/calm/8.webp'),
    require('@/assets/images/calm/9.webp'),
    require('@/assets/images/calm/10.webp'),
    require('@/assets/images/calm/11.webp'),
    require('@/assets/images/calm/12.webp'),
    require('@/assets/images/calm/13.webp'),
    require('@/assets/images/calm/14.webp'),
    require('@/assets/images/calm/15.webp'),
    require('@/assets/images/calm/16.webp'),
    // ... так само для всіх інших (energy, focus, money)
  ],
  // Додай інші папки за аналогією
};